"""empty message

Revision ID: 471a9b30a283
Revises: 47e0f3050577
Create Date: 2014-02-06 14:09:40.971000

"""

# revision identifiers, used by Alembic.
revision = '471a9b30a283'
down_revision = '47e0f3050577'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
