"""empty message

Revision ID: 47e0f3050577
Revises: None
Create Date: 2014-02-06 14:03:58.950000

"""

# revision identifiers, used by Alembic.
revision = '47e0f3050577'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ForumMessage', sa.Column('editor_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ForumMessage', 'editor_id')
    ### end Alembic commands ###
