"""empty message

Revision ID: 5265375a5461
Revises: 471a9b30a283
Create Date: 2014-02-06 14:33:57.305000

"""

# revision identifiers, used by Alembic.
revision = '5265375a5461'
down_revision = '471a9b30a283'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
